server {
    listen 80;
    listen 443 ssl;

    ssl_certificate     /etc/ssl/cert.crt;
    ssl_certificate_key /etc/ssl/cert.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www;

    location / {
        try_files $uri @rewrite;
    }

    location @rewrite {
        rewrite ^/(.*)$ /index.html;
    }

    location /proxy {
        resolver 8.8.8.8;
        set $url $arg_url;
        proxy_pass $url;
    }
}